spring.application.name=Stdcoreservices
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5000/studentdb
spring.datasource.username=postgres
spring.datasource.password=Arjun@1307

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.swagger-ui.path=/swagger-ui.html

jwt.secret=mySecretKeyForStudentManagementSystem2026
